# application.yml
# YML文件格式是YAML (YAML Aint Markup Language)编写的文件格式,YAML是一种直观的能够被电脑识别的的数据数据序列化格式,他并且容易被人类阅读.
# 注意：yml的缩进，使用空格符，而不要使用tab键

# 应用相关信息
info:
    app.name: spring-boot-demo1
    app.description: ${app.name}

# 服务器设置（端口等）
server:
    port: 9999 # 0:随机端口, -1表示禁止HTTP端口
    undertow:
        accesslog:
            enabled: true

# 日志相关
logging:
    level: DEBUG
    file: ${info.app.name}.log

# 管理监控点设置
endpoints:
    enabled: true
    sensitive: false
    cors:
        allowed-origins: http://example.com
        allowed-methods: GET,POST
    actuator:
        id: actuator
        path: /actuator
        enabled: true
        sensitive: true
    autoconfig:
        id: autoconfig
        path: /actuator/autoconfig
        enabled: true
        sensitive: true
    beans:
        id: beans
        path: /actuator/beans
        enabled: true
        sensitive: false
    configprops:
        id: configprops
        path: /actuator/configprops
        enabled: true
        sensitive: true
    docs:
        id: docs
        path: /actuator/docs
        enabled: true
        sensitive: true
    dump:
        id: dump
        path: /actuator/dump
        enabled: true
        sensitive: true
    env:
        id: env
        path: /actuator/env
        enabled: true
        sensitive: true
    flyway:
        id: flyway
        path: /actuator/flyway
        enabled: true
        sensitive: true
    health:
        id: health
        path: /actuator/health
        enabled: true
        sensitive: true
        # 缓存时间（毫秒）
        time-to-live: 1000
    info:
        id: info
        path: /actuator/info
        enabled: true
        sensitive: true
    liquibase:
        id: liquibase
        path: /actuator/liquibase
        enabled: true
        sensitive: true
    logfile:
        id: logfile
        path: /actuator/logfile
        enabled: true
        sensitive: true
    metrics:
        id: metrics
        path: /actuator/metrics
        enabled: true
        sensitive: true
    mappings:
        id: mappings
        path: /actuator/mappings
        enabled: true
        sensitive: true
    shutdown:
        id: shutdown
        path: /actuator/shutdown
        enabled: true
        sensitive: true
    trace:
        id: trace
        path: /actuator/trace
        enabled: true
        sensitive: true

# oncon相关配置
oncon:
    app:
        appid: yx_appid20161206120001001
        secret: 1234567890ABCEDF
        openid: op_9fa689beda4a0000
    user:
        enterNum: 9811000094516753
        enterNodeId: 110659027
        superAdminMobile: 18610297934
        sessionId: 9811000094516753
        busiSuperNodeId: 110659069
    redis:
        topic:
            token: topic:com:sitech:onloc:xjfhj:oncon:token
    httpserver:
        token: http://jk.teamshub.com/oncon-service/token?grant_type=sys_credential&appid={0}&secret={1}
        onconSetSessionId: http://jk.teamshub.com/oncon-service/setSessionId/{0}?access_token={1}
        onconSessionCredential: http://jk.teamshub.com/oncon-service/session_credential/{0}/{1}?access_token={2}

# redis相关
spring:
    redis:
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1
        cluster:
            nodes:
                - 192.168.2.210:7000
                - 192.168.2.210:7001
                - 192.168.2.210:7002
                - 192.168.2.210:7003
                - 192.168.2.210:7004
                - 192.168.2.210:7005
---
spring:
    datasource:
        url: jdbc:mysql://192.168.2.60:3306/paycore?serverTimezone=UTC&characterEncoding=utf-8
        username: paycore
        password: paycore111
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5Dialect

---
spring:
    rabbitmq:
        host: 10.16.31.78
        port: 5672
        virtualHost: dev
        username: dev
        password: dev